package com.etdon.winjgen;

public enum TokenType {

    KEYWORD,
    RETURN_TYPE,
    STRUCT_NAME,
    FUNCTION_NAME,
    PARAMETERS_START,
    PARAMETERS_END,
    OPENING_SQUARE_BRACKET,
    CLOSING_SQUARE_BRACKET,
    OPENING_CURLY_BRACKET,
    CLOSING_CURLY_BRACKET,
    FLOW,
    TYPE,
    PARAMETER_NAME,
    SEPARATOR,
    SEMICOLON

}
